Boekingssysteem/Controllers/DocentController.cs
using Boekingssysteem.Areas.Identity.Data;
using Boekingssysteem.Data;
using Boekingssysteem.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System;
using Boekingssysteem.Models;

namespace Boekingssysteem.Controllers
{
    [Authorize]
    public class DocentController : Controller
    {
        private readonly BoekingssysteemContext _context;

        private readonly UserManager<CustomUser> _userManager;

        public DocentController(BoekingssysteemContext context, UserManager<CustomUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            CustomUser docent = await _userManager.FindByEmailAsync(User.Identity.Name);

            DocentStatusViewModel viewModel = new DocentStatusViewModel();
            viewModel.Status = docent.Status;
            viewModel.BeginDatum = DateTime.Now;
            viewModel.EindDatum = DateTime.Now;
            viewModel.AfwezigheidId = -1;
            viewModel.DocentId = docent.Id;
            viewModel.Afwezigheden = _context.Afwezigheden.Where(a => a.Rnummer == docent.Id).ToList();

            return View(viewModel);
        }

        public async Task<IActionResult> StatusWijzigen()
        {
            CustomUser docent = await _userManager.FindByEmailAsync(User.Identity.Name);

            if (docent == null) { return NotFound(); }

            if (docent.Status == null) 
            {
                docent.Status = true; 
            } 
            else
            {
                docent.Status = !docent.Status;
            }

            _context.Update(docent);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Afwezigheden(DocentStatusViewModel vm)
        {
            CustomUser docent = await _userManager.FindByEmailAsync(User.Identity.Name);

            if (!ModelState.IsValid)
            {
                vm.Afwezigheden = _context.Afwezigheden.Where(a => a.Rnummer == docent.Id).ToList();
                return View("Index", vm);
            }

            try
            {
                Afwezigheid afwezigheid;

                if (vm.AfwezigheidId < 0)
                    afwezigheid = new Afwezigheid();
                else
                    afwezigheid = _context.Afwezigheden.First(a => a.AfwezigheidId == vm.AfwezigheidId);

                afwezigheid.Rnummer = vm.DocentId;
                afwezigheid.Begindatum = vm.BeginDatum;
                afwezigheid.Einddatum = vm.EindDatum;
                afwezigheid.Opmerking = vm.Opmerking;

                if (vm.AfwezigheidId < 0)
                    _context.Afwezigheden.Add(afwezigheid);
                else
                    _context.Afwezigheden.Update(afwezigheid);

                _context.SaveChanges();
            }
            catch (Exception e)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ActionName("DeleteAfwezigheid")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> VerwijderAfwezigheidConfirm(string id)
        {
            Afwezigheid afwezigheid = _context.Afwezigheden.First(a => a.AfwezigheidId == int.Parse(id));
            _context.Afwezigheden.Remove(afwezigheid);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Boekingssysteem/Views/Docent/Index.cshtml
@model Boekingssysteem.ViewModels.DocentStatusViewModel;
@{
    ViewData["Title"] = "Status en afwezigheden";
}

<div class="row">
    <div class="col-md-6">
        <h1>@ViewData["Title"]</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4" style="text-align:center">
        <h5>Status</h5>
        <a asp-controller="Docent" asp-action="StatusWijzigen" type="button" id="statusBtn" class="btn @Model.GetButtonColor()">@Model.GetStatus()</a>
    </div>

    <div class="col-md-4"></div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="row">
            <form asp-action="Afwezigheden" method="post" class="form-inline justify-content-center">
                <input type="hidden" asp-for="AfwezigheidId" id="afwezigheidId" />
                <input type="hidden" asp-for="DocentId" />
                <input type="hidden" asp-for="Status" />
                <div asp-validation-summary="ModelOnly" class="text-danger" />
                <div class="row formRow col-10">
                    <div class="form-group">
                        <label class="form-label" for="beginDatum">Begindatum</label>
                        <input type="date" class="form-control" id="beginDatum" asp-for="BeginDatum" class="form-control" />
                        <span asp-validation-for="BeginDatum" class="text-danger"></span>
                    </div>
                </div>
                <div class="row formRow col-10">
                    <div class="form-group">
                        <label class="form-label" for="eindDatum">Einddatum</label>
                        <input type="date" class="form-control" id="eindDatum" asp-for="EindDatum" class="form-control" />
                        <span asp-validation-for="EindDatum" class="text-danger"></span>
                    </div>
                </div>
                <div class="row formRow col-10">
                    <div class="form-group">
                        <label class="form-label" for="opmerking">Opmerking</label>
                        <input type="text" class="form-control" id="opmerking" asp-for="Opmerking" class="form-control" />
                    </div>
                </div>
                <br>
                <input type="submit" class="btn btn-primary" value="Bevestig" />
            </form>
        </div>
    </div>

    <div class="col-md-8" style="margin-top:40px">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Begindatum</th>
                    <th scope="col">Einddatum</th>
                    <th scope="col">Opmerking</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (Afwezigheid afwezigheid in Model.Afwezigheden)
                {
                    string modalId = "modal" + afwezigheid.AfwezigheidId;
                    var showModal = Html.Raw($"showModal('modal{afwezigheid.AfwezigheidId}')");
                    var afwezigheidBewerken = Html.Raw($"afwezigheidBewerken('{afwezigheid.Opmerking}', '{afwezigheid.Begindatum.ToShortDateString()}', '{afwezigheid.Einddatum.ToShortDateString()}', '{afwezigheid.AfwezigheidId}')");
                    <tr>
                        <td>@afwezigheid.Begindatum.ToShortDateString()</td>
                        <td>@afwezigheid.Einddatum.ToShortDateString()</td>
                        <td>@afwezigheid.Opmerking</td>
                        <td>
                        <span>
                            <button id="@afwezigheid.AfwezigheidId" type="button" onclick="@afwezigheidBewerken" class="btn btn-primary input-group-append"><i class="fa fa-edit"></i></button>
                        </span>
                        <span>
                            <button type="button" class="btn btn-danger input-group-append" data-toggle="modal" data-target="#@modalId"><i class="fa fa-trash"></i></button>
                        </span>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>

@foreach (Afwezigheid afwezigheid in Model.Afwezigheden)
{
    <!-- TO DO -->
    <!-- Modal delete afwezigheid -->
    string modalId = "modal" + afwezigheid.AfwezigheidId;
    <div class="modal fade" id="@modalId" tabindex="-1" role="dialog" aria-labelledby="linkModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="beheerModalLabel">Verwijder Afwezigheid</h5>
                </div>
                <div class="modal-body">
                    Ben je zeker dat je deze afwezigheid wil verwijderen?
                </div>
                <div class="modal-footer">
                    
                    <form class="mt-5" asp-controller="Docent" asp-action="DeleteAfwezigheid" asp-route-id="@afwezigheid.AfwezigheidId">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <input  type="submit" class="btn btn-primary" value="Bevestig"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
 }

 <script>
    const begindatum = document.getElementById("beginDatum");
    const einddatum = document.getElementById("eindDatum");
    const opmerking = document.getElementById("opmerking");
    const afwezigheidId = document.getElementById("afwezigheidId");

    function datumFormateren(datumArr) {
        for (let i = 1; i < datumArr.length; i++) {
            let dagOfMaand = datumArr[i];

            if (dagOfMaand.length < 2) {
                datumArr[i] = '0' + dagOfMaand;
            }
        }

        return datumArr.join('-');
    }


    function afwezigheidBewerken(beschrijving, eersteDatum, tweedeDatum, id) {
        begindatum.value = datumFormateren(eersteDatum.split('-').reverse());
        einddatum.value = datumFormateren(tweedeDatum.split('-').reverse());
        opmerking.value = beschrijving;
        afwezigheidId.value = id;
    }
 </script>